### PR TITLE
[ios/android] Add code format to result object

### PR DESCRIPTION
**Pull request by NotProf**
image

### CODE REVIEW

**Comment by tafelnl** [comment]
Thanks for the PR. Do Android and iOS both return the same values? I suspect there might be some small discrepancies right?

**Comment by NotProf** [comment]
> Thanks for the PR. Do Android and iOS both return the same values? I suspect there might be some small discrepancies right?

Yes, you're right, this is due to the features of the formats in the IOS, but most of popular formats are displayed the same

**Comment by tafelnl** [comment]
I think to be consistent we should return the format the same way as in the input formats: https://github.com/capacitor-community/barcode-scanner#target-only-specific-barcodes

Do you happen to have the ability to edit this PR so that it supports that.

For reference you could take a look at, and use these maps in the code: [Android](https://github.com/capacitor-community/barcode-scanner/blob/e8ba33fad024725f34711217dc1508bd49b16144/android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java#L53) and [iOS](https://github.com/capacitor-community/barcode-scanner/blob/ca12c0540c570c2d2bb65a39aa3d003be64b1984/ios/Plugin/Plugin.swift#L70)

**Comment by NotProf** [comment]
@tafelnl I changed my PR using the names of this map

**Comment by tafelnl** [comment]
Awesome, I'll test it out and merge! Thanks again.

**Pull request closed without merging**
