### PR TITLE
Feat/viewfinder

### PR DESCRIPTION
**Pull request by cesaredifoggiadev**
In this pr I have included the possibility of setting an intermediate frame where the barcode is read, externally to the plugin so you can set a box where the barcode will be read.
To add the viewframe just set the parameters
`wait BarcodeScanner.startScan({
    cords: [466, (window.innerHeight - 50) / 2], // x, y
    width: 400,
    height: 100
  })`

### CODE REVIEW

**Comment by thegnuu** [comment]
I am currently on vacation, please give me some time to review this changes and merge it. Thanks a lot :)

**Comment by cesaredifoggiadev** [comment]
Hi @thegnuu  if you have any problems for this pr, I can help you, thank you so much!

**Comment by thegnuu** [comment]
@cesaredifoggiadev thanks a lot for your work on this one! I had a similar idea in mind on my ml-kit branch but I reversed it and sent the coordinates and dimensons of the scanned code back since this is (I assume at least) the only way that works with ml-kit.

This solution looks good for this version of the plugin, have you already found a way to achieve the same on Android as well?

**Comment by cesaredifoggiadev** [comment]
i have two ideas to implements in this featur, the first is to add a rect box in native code, and set the dimensions of the box with cords, width and height parameters, the second is to add a rect in html code and set the height and width with css.

For android i don't have the knowledge for introduce this feature, but I can examine a solution. When you return from the vacation, we can organize a meet.

**Comment by cesaredifoggiadev** [comment]
Happy holidays @thegnuu !

**Comment by thegnuu** [comment]
@cesaredifoggiadev Sorry for my delayed answer, lots of work at the moment.

As I previously said it would make lots o sense to have a feature like this, but I think that the Android version should have the same behaviour as the iOS version before we can merge this feature to the main branch.

My idea of this implementation originally was not to change the scanning-view itself, i would have just returned the "found coordinates" and let the devs decide which codes should be used and which should be omitted. But this would require different interfaces as in the `ml-kit` branch. Since the UI should be created by any dev on their own this looked like the easiest solution.

But if you can find a way that works the same way on Android as your proposed iOS version, I am happy with this solution as well :)

**Comment by arcadius** [comment]
Thank you very much @cesaredifoggiadev and @thegnuu  for this PR.

Any update about this one please

**Comment by thegnuu** [comment]
@arcadius unfortunately not, since this is not compatible with the changes done regarding the `ml-kit` implementation I need to come back to it once the other stuff is done.

Maybe we can use some parts of it or provide some sort of similar functionality based on this PR.

**Comment by thegnuu** [comment]
@cesaredifoggiadev Unfortunately I cannot port these changes to the upcoming `ml-kit` release which is currently in pre-release.

Thank you anyway very much for your work on this!

**Pull request closed without merging**
