### PR TITLE
Continuous scanning on iOS and Android

### PR DESCRIPTION
**Pull request by JanMisker**
Probably not fully ready for merging yet, mainly because I implemented only iOS for now.
Also some discussion might be needed on the new methods.

To initiate a continuous scan, `startScanning(options, callback)` should be called. This reuses the same `ScanOptions` `prepare()` and `scan()` functionality as `startScan(options)`. The only difference is that the `keepAlive` is set to true on the `CAPPluginCall` and of course that a callback function will be called with the results. When a code is recognised there is a check on the `keepAlive` to determine whether we are in single scan or continuous scan mode, main difference being that in single scan mode the camera is destroyed. 

Also added are methods to pause and resume the scanning.

### CODE REVIEW

**Comment by cies** [comment]
I've tested this on two iOS devices and it works like a charm!

**Comment by JanMisker** [comment]
Also implemented for Android now, would like to get some feedback if this is the right direction. If yes I will add documentation as well.

**Comment by thegnuu** [comment]
Are there any reasons this PR is not merged now and if so is there a way I can help you guys somehow?

Thanks a lot!

**Comment by JanMisker** [comment]
@thegnuu I'm not sure, I never got any feedback on this and other PRs. 

There are no instructions on how to communicate with the maintainer. Maybe tagging them here helps? @tafelnl ??

**Comment by thegnuu** [comment]
@JanMisker this is weird, but it seems there are a few useful PRs open in the same state...

@tafelnl I would as well offer to help maintain the repo since we need it in one of our main applications in the future....

**Comment by JEVietti** [comment]
I could also really use this and the other pull requests @JanMisker has made to me merged, for use in my applications.  @tafelnl

**Comment by thegnuu** [comment]
I tried reaching out to ionic to somehow get access to this repo as an additional maintainer, unfortunately without any success until now. I will try it again if I don't hear anything from them....

**Comment by thegnuu** [comment]
@JanMisker & @JEVietti I should be added as a maintainer soon 👍🏼 

It will still take me a few days to free some time to check out all the open PRs but I should be able merge this stuff sometimes next week.

**Comment by tafelnl** [comment]
I am so sorry guys. I really lack the time to be a maintainer of this repository. I would really love to help and even bring out complete rewrite. But I simply don't have the time right now 😔 (as I do have a lot of work on my hands, among which is maintaining this library: https://github.com/DutchConcepts/capacitor-google-maps/tree/next). So if someone on the Capacitor team can add @thegnuu as a maintainer, that would be great indeed.

**Comment by thegnuu** [comment]
@tafelnl no worries! I totally understand that there are sometimes other priorities :)

I am pretty new to capacitor (at least the native stuff of it) but I will do my best to help out - but for a complete rewrite I am not ready now I guess ;)

**Comment by JanMisker** [comment]
@tafelnl thanks for getting back to us 👍 (ps: I'm also in NL ;-)

I'm happy to contribute, we recently moved an app from Cordova to Capacitor, utilizing this plugin. I'm happy to help out in the maintenance of this library together with @thegnuu.

**Comment by JEVietti** [comment]
@thegnuu @JanMisker Any progress on this getting merged?

**Comment by JanMisker** [comment]
> @thegnuu @JanMisker Any progress on this getting merged?

I wasn't added as a contributor, we have to wait for @thegnuu

**Comment by thegnuu** [comment]
@JanMisker @JEVietti I reserved a few hours next week to work on this project. If there are no unforeseen issues I should be able to merge the currently open PRs by the end of next week!

**Comment by thegnuu** [comment]
@JanMisker Thanks a lot! I merged the changes manually since the commit were not signed. The repo is setup to require signed commits and somehow I am to stupid to simply merge the changes other-ways ;)

Anyway, i will merge some of the other PRs today and will test all the changes at once next week, once things are working on my devices i will create `2.1.0` with some of the PRs!

**Comment by JanMisker** [comment]
> @JanMisker Thanks a lot! I merged the changes manually since the commit were not signed. The repo is setup to require signed commits and somehow I am to stupid to simply merge the changes other-ways ;)
> 
> Anyway, i will merge some of the other PRs today and will test all the changes at once next week, once things are working on my devices i will create `2.1.0` with some of the PRs!

Thanks for taking the time to work on this!
Feel free to reach out if you need some help, I think easiest is to just tag me in an issue.

**Pull request closed without merging**
