### PR TITLE
Capacitor v4 dependencies upgraded

### PR DESCRIPTION
**Pull request by melihgunduz**
I didn't do detailed testing but after upgrading the version numbers the scan worked normal. (The previous one was deleted by mistake, I uploaded it again) #132

### CODE REVIEW

**Comment by thegnuu** [comment]
You closed it for some reason ;) Thanks for adding it again!

**Comment by joeldhenry** [comment]
The PR looks good! Can you merge it in?

**Comment by thegnuu** [comment]
Unfortunately not, someone decided that only signed commits can be merged in this repo, but I will prepare the Capacitor 4 update today and create a release :)

**Comment by thegnuu** [comment]
See #137 :)

**Pull request closed without merging**
