### PR TITLE
Integrator view

### PR DESCRIPTION
**Pull request by ADMIADev**
Possibility to use IntentIntegrator for android. IntentIntegrator has better performance for 2D Barcodes. Tested with Code-39.

### CODE REVIEW

**Comment by ADMIADev** [comment]
As discussed in #69

**Comment by thegnuu** [comment]
Just wanted to let you know that I am aware of this PR and I will look into it!

There are a lot of other PRs right now and I think they have a higher priority for the community.
Since this PR will only "fix" the issue for 1D codes on android and we have issues open for this on iOS as well I have to check out possible solutions anyway, when I do this I will check out your PR and if it is a good solution I will merge it of course. As @tafelnl said in the issue the different UI-styling behaviour is not ideal since the UI is currently confusing users anyway ;)

**Comment by thegnuu** [comment]
@ADMIADev I will work on #107 first, if this works as currently expected I don't think that this PR will be required anymore :)

**Comment by thegnuu** [comment]
@ADMIADev Since the new version of this plugin will move to `ml-kit` I am not able to backport these changes. Thank you anyway a lot for your idea and your work!

**Pull request closed without merging**
