### PR TITLE
[android] add support for torch.

### PR DESCRIPTION
**Pull request by tripodsgames**
Added support for torch on android.

Enable Torch
`BarcodeScanner.enableTorch();`

Disable Torch
`BarcodeScanner.disableTorch();`

### CODE REVIEW

**Comment by tafelnl** [comment]
Thanks for the PR. I will look into it.

I see that you commented this line: https://github.com/capacitor-community/barcode-scanner/pull/24/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R6 

Could you undo this? This is needed for the npm package publishment

**Comment by tripodsgames** [comment]
> Thanks for the PR. I will look into it.
> 
> I see that you commented this line: https://github.com/capacitor-community/barcode-scanner/pull/24/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R6
> 
> Could you undo this? This is needed for the npm package publishment

Sure!

> Thanks for the PR. I will look into it.
> 
> I see that you commented this line: https://github.com/capacitor-community/barcode-scanner/pull/24/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R6
> 
> Could you undo this? This is needed for the npm package publishment

I've updated the gitignore

**Comment by vosecek** [comment]
Nice, when it will be available to update?
Barcode scanner plugin blocks using Android torch in system or switch on flashlight using cordova-flashlight-plugin.

iOS works good with cordova-flashlight-plugin and this one.

**Comment by tafelnl** [comment]
Would you be able to sign the commits? This is required by the Capacitor team. If not, I will try to do it myself this weekend.

**Comment by tripodsgames** [comment]
> Thanks for the PR. Would you be able to sign the commits? This is required by the Capacitor team. If not, I will try to do it myself this weekend.

Done it.

**Comment by tripodsgames** [comment]
@tafelnl all commits are now signed.

**Comment by vosecek** [comment]
> Thanks for the PR. Would you be able to sign the commits? This is required by the Capacitor team. If not, I will try to do it myself this weekend.

Any progress about it? Its possible to have this feature available in capacitor package soon?

Thanks a lot

**Comment by tafelnl** [comment]
Thanks @tripodsgames for signing the commits. Would you be able to select this option:

image

I'd like to make some small changes and add iOS support as well.

**Comment by tripodsgames** [comment]
> Thanks @tripodsgames for signing the commits. Would you be able to select this option:
> 
> image
> 
> I'd like to make some small changes and add iOS support as well.

I think this options is not available for organizations.
Going to make another pull request.

**Pull request closed without merging**
