### PR TITLE
[Android] Add Continuous Focus Mode to improve code recognition performance

### PR DESCRIPTION
**Pull request by longlife1st**
Added Continuous Focus Mode for camera focus in order to improve code recognition performance on some devices where it is required.
Will only be enabled if the device supports it.

Aims to fix https://github.com/capacitor-community/barcode-scanner/issues/27

### CODE REVIEW

**Comment by tafelnl** [comment]
Thanks for the PR. Would you be able to sign the commits? This is required by the Capacitor team. If not, I will try to do it myself this weekend.

**Comment by longlife1st** [comment]
@tafelnl I wasn't aware of that requirement, but I will take care of it.

**Comment by longlife1st** [comment]
@tafelnl I have added new signed version of the commit, but seems the non-verified commit remained in history.
If necessary, I can just move the commit to a new branch if required, just let me know.

**Comment by tafelnl** [comment]
Yes, it is required that _all_ commits are signed. So that means it should be signed retroactively. Thank you for the effort you put into this!

**Comment by longlife1st** [comment]
Let me recreate a new PR then.

**Pull request closed without merging**
