### PR TITLE
setting mBarcodeView to null when camera is dismantled

### PR DESCRIPTION
**Pull request by nick-krantz**
Setting mBarcodeView to null when camera is dismantled to avoid for the barcode-scanner to open camera if the app is backgrounded and then foregrounded again. 
When an app is resumed Capacitor goes through all plugins to alert them that the app has been resumed, because mBarcodeView is never set to null when it is dismantled, the view attempts to open the camera when it isn't in use. This can cause issues with other plugins that need to access the camera.

### CODE REVIEW

**Comment by tafelnl** [comment]
Thanks for looking into this and submitting a PR. Just to be sure: did you check for any possible side effects?

**Comment by nick-krantz** [comment]
> I was only able to test on Android 11.

I had the chance this morning and tested on Android 9, with the same results. No side effects.

**Comment by nick-krantz** [comment]
@tafelnl Signed!

**Comment by tafelnl** [comment]
Thanks a lot!

**Comment by nick-krantz** [comment]
Thanks @tafelnl, is there a planned release date so this can be consumed?

**Pull request merged**
