### PR TITLE
Feature/torch

### PR DESCRIPTION
**Pull request by dkliemsch**
Adding torch functions for android and iOS to enable, disable and toggle the torch and also a method to get the current torch state.

### CODE REVIEW

**Comment by DelemarreA** [comment]
Is it posible to merge this functionality?

**Review by jdiaz49 — APPROVED** [review]

**Comment by thegnuu** [comment]
Merge manually because the repo is setup to only allow signed commits (don't know why to be honest but I don't have the permission to change it)

Thank you @dkliemsch !

**Comment by arnotixe** [comment]
awwww-sum :partying_face: 
I went through the trouble of setting up signing on my commits, but I totally agree this is the better implementation. Can't wait for it to be available and ease building of my app!

**Comment by ali-hasan** [comment]
Hi guys, thank you so much for amazing plugin. 

It seems from version 2.0.1 there's support for torch. I'm currently using version 2.1.1 but for me torch does not get enabled during the scan. I'm testing it on Android device. Scanner works perfectly but torch never get enabled. I also added `FLASH` and `Camera.Hardware` permissions in `AndroidManifest.xml` but still no luck. Do you guys know what could i be missing here?

Thank you so much for any help.

**Pull request closed without merging**
